apiVersion: v2
name: etcd-backup
description: Create a CronJob that performs ETCD Backup and stores the backup to a PV.
version: 1.0.0
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - security
  - backup
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: B677CB52F8358FA091044E375D24D6846DBA8F8A
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/B677CB52F8358FA091044E375D24D6846DBA8F8A
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
    - kind: added
      description: added dependency tp tpl library