---
# Examples values file

# -- If you want this component to only run on specific nodes, you can
# configure tolerations of tainted nodes.
# <br />
# Example include:
# {{- if .Values.tolerations }}
# {{ include "tpl.tolerations" .Values.tolerations  | indent 0 }}
# {{- end }}
tolerations:
  - effect: NoSchedule
    key: infra
    operator: Equal
    value: reserved
    tolerationSeconds: 600
  - effect: NoSchedule
    key: infra
    operator: Equal
    value: reserved
    tolerationSeconds: 600

# -- If you want to define resources
# <br />
# Example include:
# {{- if .Values.resources }}
# {{ include "tpl.resources" .Values.resources  | indent 0 }}
# {{- end }}
resources:
  requests:
    cpu: 4
    memory: 8
    ephemeral-storage: 50
  limits:
    cpu: 8
    memory: 16
    ephemeral-storage: 500

nodeSelector:
  key: node-role.kubernetes.io/infra
  value: ''

# -- If you want to annotate a namespace to run on a specific node configure the following annotations
# <br />
# Example include:
#    {{- if .Values.namespace.bindtoNode }}
#    {{- if .Values.namespace.bindtoNode.role }}
#    {{- include "tpl.bindtoNode" .Values.namespace.bindtoNode | nindent 4 }}
#    {{- end }}
#    {{- end }}

namespace:
  bindtoNode:
    role: infra

# -- Define a NamespaceSelector and the required labels
# <br />
# Example include (used in chart admin-networkpolicies)
#
#spec:
#  subject:
#    {{- if .subject.namespaces }}
#    namespaces:
#      {{- if .subject.namespaces.matchExpressions }}
#      matchExpressions:
#        {{- range .subject.namespaces.matchExpressions }}
#        {{- include "tpl.matchExpressions" . | indent 4 }}
#        {{- end }}
#      {{- end }}
#      {{- if .subject.namespaces.matchLabels }}
#      {{- include "tpl.matchLabels" .subject.namespaces.matchLabels | indent 4 }}
#      {{- end }}
#    {{- end }}
namespaceSelector:          
  matchLabels:
    kubernetes.io/metadata.name: "openshift-dns"

# -- Deine a metchExpression to use key, oeprator, value pairs.
# <br />
# Example include (used in chart admin-networkpolicies)
#
#spec:
#  subject:
#    {{- if .subject.namespaces }}
#    namespaces:
#      {{- if .subject.namespaces.matchExpressions }}
#      matchExpressions:
#        {{- range .subject.namespaces.matchExpressions }}
#        {{- include "tpl.matchExpressions" . | indent 4 }}
#        {{- end }}
#      {{- end }}
#      {{- if .subject.namespaces.matchLabels }}
#      {{- include "tpl.matchLabels" .subject.namespaces.matchLabels | indent 4 }}
#      {{- end }}
#    {{- end }}
matchExpressions:    
  - key: kubernetes.io/metadata.name
    operator: NotIn
    values:
      - "kube-system"
      - "openshift*"
      - "default"
      - "kubde-info" 